#+TITLE: Probability 2
- Recap: probability foundations
  - Mathematical foundations of the probability theory rely on a
    two-step approach to describing events to which we assign
    probabilities:
    - *Sample Space* is the set of all possible outcomes of an experiment. Examples:
      - when tossing a coin, the sample space is $\{H,T\}$
      - rolling a die: $\{1,2,3,4,5,6\}$
      - tossing two coins: $\(H,H),(H,T),(T,H),(T,T)\}$
      - measuring the lifetime of a car engine: the sample space is $[0,\infty)$
    - *Event space* is a set of subsets of the sample space, where we
      choose what events are relevant purposes of our model. Examples:
      - tossing a coin: we have a choice of contructing event space as
        simply $\{\emptyset,\{H,T\}\}$ --- meaning ``coin was tossed
        (with the outcome of heads, or tails, but I don't care which",
        or not (the empty set). More commonly, we have in mind the
        event space $\{\emptyset, \{H\}, \{T\}, \{H,T\}\}$ --- which
        distinguishes the event 'heads' from event 'tails'.
      - measuring the lifetime of a car engine: we can set up an event
        space $\{\emptyset, [0,10), [10,\infty), [0,\infty)\},
        corresponding to events ``engine lives to the warranty
        lifetime of 10, or not".
      - Note that we always include the empty set (nothing happens)
        and the entire sample space (something happens). Moreover,
        when we construct the event space, we require that the
        complement of an event $A$ is also an allowable event ($A$
        does not happen), and so are union ($A$ or $B$ happen) and
        intersection (both $A$ and $B$ happen) of two events $A$ and
        $B$.
      - For most examples here, we can take the event space to be the
        /power set/ of the sample space - i.e., any subset of the
        sample space is an allowable event. This is not always
        possible for infinite sample spaces --- and the reasons why
        are the main reason why we insist on separating the concepts
        of sample and event spaces.
      - Exercises:
        - write down the event space for tossing two coins, if we
          don't care which order heads and tails come up.
          - Answer: e.g. $\{\emptyset,\{H\},\{T\},\{H,T\}\}$
- Random walk on a Grid
  - My friend and I just realized we are both visiting the city of
    Mathville, but are staying at different hotels. My hotel is $n=10$
    blocks to the East and $n=10$ blocks to the South of my
    friend's. We agreed to meet but forgot to specify where. We both
    leave our hotels at the same time in the morning. At each
    intersection, I decide, with equal probability, to continue North
    or East, while my friend decides, also with equal probability, to
    continue South or West at each intersection. We walk with the same
    speed.
    - What is the probability that we meet?
      - With even number of blocks in both directions, we can only
        meet on an intersection. We would have to have walked the same
        distance, so the 10 possible meeting places are the grid
        points on the diagonal of the $10\times10$ square. We now need
        to count how many ways there are to arrive at each of them.
        - endpoints $(10,0)$ and $(0,10)$: only one way
        - $(1,9)$: 10 ways, since there are 10 chances for me to turn
          North. Similarly for $(9,1)$.
        - $(i,j)$: the binomial coefficient ${{10}\choose{i}}$ Note
          that this is the same as ${{10}\choose{j}}$, and $i+j=10$.
    - Now suppose I leave my hotel $k=4$ minutes late. What is the
      probability that we meet now?
    - If $n=1$ and $k=1$, what is the probability of us meeting?
- joint & marginal probabilities
- Bayes' theorem
- decision trees
- Binomial distribution
- Geometric Distribution
- means and variance
- mean vs median
  - salaries/lottery
- inclusion/exclusion principle
- Unfair Coin
  - Suppose we toss an unfair coin which comes up heads with
    probability $p=0.45<\frac{1}{2}$. Your friend says that you can
    only bet on heads, and the winner is the one who has greater score
    at the end of several rounds. He will let you choose the number of
    rounds, as long as it's even. What number should you choose?
  - Since each round is stacked against you, the best option would be
    to play as few rounds as possible. The next consideration is that
    with even number of rounds, there's a possibility of a draw.
- keyring
  - I have 20 keys on my keyring. I came home late last night, and
    discovered that the light bulb over my door in not working.
    - If I start going through the keys, each time trying one that I
      have not tried before, what is the probability of finding the
      correct key on the 4th attempt?
      - p(correct key on n^{th} attempt)
          = p(previous attempts didn't work) $\times \frac{1}{K-n}
          = \left(1-\frac{1}{K}\right)\mdots\left(1-\frac{1}{K-(n-1)}\right)\cdot\frac{1}{K-n}
          = \frac{(K-1)(K-2)\mdots(K-n)}{K(K-1)(K-2)\mdots(K-n)}=\frac{1}{K}$
        - Should we be surprised by the answer of $\frac{1}{K}$ for any
          of the first $K$ attempts? Shouldn't we expect to find the
          right key with a higher probability towards the end of the
          process, when the keyring is almost exhausted? Why yes, the
          probability of finding the right key grows the smaller the
          keyring gets, but /so does the probability of already found
          the right key in previous attempts/.
        - Another way of thinking about this is: if we arrange the keys
          in a row, the correct one will be in any given position with
          probability $\frac{1}{K}$ - and this corresponds exactly to
          trying the keys one-by-one without replacement.
    - What if now, at each attempt, I choose a random key from the
      entire keyring, including the ones I already tried?
      - Again, $p({\rm correct key on }n^{th}{\rm attempt})
         = p({\rm previous attempts didn't work}) \times \frac{1}{K}
         = \left(1-\frac{1}{K}\right)^{n-1} \frac{1}{K}$
        - As a sanity check, let's verify that the probabilities add up to one:
          $\frac{1}{K}\times\sum_{n=0}^\infty \left(1-\frac{1}{K}\right)^{n}
            = \frac{K-1}{K} \frac{1}{1-1+\frac{1}{K}} = 1$
    - Finally, what if I'm choosing from the entire keyring, except
      the one key I have just tried?
      - $p = \left(1-\frac{1}{K-1}\right)^{n-1}\frac{1}{K-1}$
      - Just need to be careful with 'edge cases' of K=1 and K=2
- The X Factor
  - In a popular math TV show, contestants solve a difficult
    mathematical problem, and each of the three maths professors on
    the panel either agrees or disagrees with the solution. A
    professor has probability $p$ of being correct in their
    evaluation. The final decision is given by the majority of the
    votes. One day, a panel member was sick, and the show management
    needed to decide whether to have an actor fill in --- who then
    would secretly toss a fair coin to give his verdict; or (to avoid
    a tie) reduce the panel to only one professor. Which method would
    be fairer?
  - Suppose we hire an artist to replace the professor.  The
    remaining two professors give correct judgement with probability
    $p^2$, in which case the artist's vote is irrelevant. If the
    professors' decisions are split, the panel would be correct with
    probability[fn::the first factor of 2 because either professor
    could be right] $2\timesp(1-p)\frac{1}{2}$. The total
    probability of the panel being correct is $p^2 + p(1-p) = p$ ---
    same as a single professor, but much more entertaining.
- Fermat Theorem
  - Suppose we have two urns, each filled with the same total number
    of black and white balls. We sample with replacement some number
    $n$ of balls from each urn. Can you find $n$ and the total
    number of the balls in each urn if we are given that the
    probability of all white balls being sampled from the first urn
    is the same as the probability of either all white or all black
    balls being sampled from the second urn?
    - if the number of white balls in the first urn is $x$, and the
      second urn contains $y$ white balls and $z$ black balls, then
      we have $$\left(\frac{x}{y+z}\right)^n =
      \left(\frac{y}{y+z}\right)^n + \left(\frac{z}{y+z}\right)^n$$,
      or $x^n = y^n + z^n$ for integer $x,y,z$, and $n$. For $n=2$
      the solutions are the so-called Pythagorean triples, such as
      e.g. $z=5,y=4,z=3$. What can you say about the case $n=1$?
- circuits
  - I've set up a circuit as on the diagram but unwisely left my
    wirecutters on the workbench where my naughty little brother can
    get them.
    - If he cuts two wires at random, what is the probability that the
      current would still flow between A and B?
      - There are $\begin{matrix}2\\5\end{matrix}=10$ pairs of wires
        in the circuit, and the loss of two of those pairs --- $AC,
        AD$ and $BC,BD$ --- would break the circuit completely. So the
        probability of current still flowing is
        $1-\frac{2}{10}=\frac{4}{5}$
    - What if he cuts three wires at random?
      - With 5 wires, choosing which three wires to cut is the same as
        choosing which pair of wires to leave alone. There are two
        pairs of wires that are enough to complete the circuit:
        $AC,CB$ and $AD,DB$. Therefore, the probability that the
        current is still flowing is $\frac{2}{10}=\frac{1}{5}$.
    - My brother is still very small and only successfuly cuts the
      wire with probability of $\frac{1}{3}$, which is independent of
      his attempts with the other wires.
      - If he tries to cut all the wires, what is the probability the
        current still flows between $A$ and $B$?
        - If 4 or more wires are cut, there's definitely no more
          current, while with one wire cut, there will definitely
          still be current flowing. He would cut two wires with
          probability
          $\begin{matrix}2\\5\end{matrix}\left(\frac{1}{3}\right)^2\left(\frac{2}{3}\right)^3$,
          and *if* that happens, there's still only $\frac{1}{5}$
          chance of disabling the circuit.
      - I come back and discover that the current is not flowing. What
        is the probability that the centre wire has been cut?
